package org.atnos.eff

object create
    extends ReaderCreation
    with WriterCreation
    with StateCreation
    with EvalCreation
    with OptionCreation
    with ListCreation
    with EitherCreation
    with ValidateCreation
    with ChooseCreation
    with FutureCreation
    with MemoCreation
    with EffCreation
    with SafeCreation

object all
    extends ReaderEffect
    with WriterEffect
    with StateEffect
    with EvalEffect
    with OptionEffect
    with ListEffect
    with EitherEffect
    with ValidateEffect
    with ChooseEffect
    with SafeEffect
    with MemoEffect
    with EffInterpretation
    with EffCreation
    with EffImplicits
