addSbtPlugin("com.jsuereth"         % "sbt-pgp"               % "1.1.1")
addSbtPlugin("com.typesafe.sbt"     % "sbt-ghpages"           % "0.6.2")
addSbtPlugin("com.typesafe.sbt"     % "sbt-site"              % "1.3.2")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"         % "1.5.1")
addSbtPlugin("com.typesafe.sbt"     % "sbt-git"               % "1.0.0")
addSbtPlugin("org.scala-js"         % "sbt-scalajs"           % "0.6.22")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"          % "2.3")
addSbtPlugin("ohnosequences"        % "sbt-github-release"    % "0.7.0")

resolvers += Resolver.url("sonatype", new URL("https://oss.sonatype.org/content/repositories/releases"))(Resolver.ivyStylePatterns)
