on:
  pull_request_target:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  show_doc_diff:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: 11
        distribution: temurin
    - uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install pandoc
      run: ./.github/install_pandoc.sh
    - uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v6.4.8
    - name: Generate html
      run: ./.github/gen_doc.sh
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        ref: gh-pages
        path: gh-pages
    - run: |
        cp -r target/specs2-reports/site/* gh-pages/
        pushd gh-pages
        git checkout -- javascript
        git diff > diff.txt
        wc -l diff.txt
        popd
    - uses: actions/github-script@v9
      with:
        script: |
          const fs = require('fs');
          const diff = fs.readFileSync("gh-pages/diff.txt").toString();
          if (diff.length === 0) {
            console.log("no diff");
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "```diff\n" + diff + "\n```"
            });
          }
