on:
  pull_request_target:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  show_doc_diff:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: 8
        distribution: temurin
    - uses: sbt/setup-sbt@ae54f7cfe46ec0d24ade661d77f007360ab48bda # v1.1.16
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install pandoc
      run: ./.github/install_pandoc.sh
    - uses: coursier/cache-action@c5ca79321d170b8a18c288d9cadc2a6037166d0f # v6.4.8
    - name: Generate html
      run: ./.github/gen_doc.sh
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: gh-pages
        path: gh-pages
    - run: |
        cp -r target/specs2-reports/site/* gh-pages/
        pushd gh-pages
        git checkout -- javascript
        git diff > diff.txt
        wc -l diff.txt
        popd
    - uses: actions/github-script@v8
      with:
        script: |
          const fs = require('fs');
          const diff = fs.readFileSync("gh-pages/diff.txt").toString();
          if (diff.length === 0) {
            console.log("no diff");
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "```diff\n" + diff + "\n```"
            });
          }
