on:
  pull_request_target:
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  show_doc_diff:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
    - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        java-version: 17
        distribution: temurin
    - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        allow-unsafe-pr-checkout: true
    - name: Install pandoc
      run: ./.github/install_pandoc.sh
    - uses: coursier/cache-action@95e5b1029b6b86e7bac033ee44a0697d8a527d2d # v6.4.8
    - name: Generate html
      run: ./.github/gen_doc.sh
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        ref: gh-pages
        path: gh-pages
        allow-unsafe-pr-checkout: true
    - run: |
        cp -r doc/target/specs2-reports/site/* gh-pages/
        pushd gh-pages
        git checkout -- javascript
        git diff > diff.txt
        wc -l diff.txt
        popd
    - uses: actions/github-script@v9
      with:
        script: |
          const fs = require('fs');
          const diff = fs.readFileSync("gh-pages/diff.txt").toString();
          if (diff.length === 0) {
            console.log("no diff");
          } else {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "```diff\n" + diff + "\n```"
            });
          }
